#!/bin/sh

WEBVMID=$(cat ~/virtualization/VMscripts/dasp4682.txt)
echo "RADO $WEBVMID"
DBVMID=$(cat ~/virtualization/VMscripts/aiiv4637.txt)
CLIENTVMID=$( cat ~/virtualization/VMscripts/ugve4191.txt)
CENDPOINT=https://grid5.mif.vu.lt/cloud3/RPC2
WEBUSER=dasp4682
echo "Please enter password for your VU MIF cloud infrastructure $WEBUSER"
stty -echo
read WEBPASS
stty echo

echo "Will delete VM $WEBVMID"
$(onevm delete $WEBVMID --user $WEBUSER --password $WEBPASS --endpoint $CENDPOINT )
echo "$WEBUSER vm deleted..."

DBUSER=aiiv4637
echo "Please enter password for your VU MIF cloud infrastructure $DBUSER"
stty -echo
read DBPASS
stty echo

echo "Will delete VM $DBVMID"
$(onevm delete $DBVMID --user $DBUSER --password $DBPASS --endpoint $CENDPOINT )
echo "$DBUSER vm deleted..."

CLIENTUSER=ugve4191
echo "Please enter password for your VU MIF cloud infrastructure $CLIENTUSER"
stty -echo
read CLIENTPASS
stty echo
echo "Will delete VM $CLIENTVMID"
$(onevm delete $CLIENTVMID --user $CLIENTUSER --password $CLIENTPASS --endpoint $CENDPOINT )
echo "$CLIENTUSER vm deleted..."

rm ~/virtualization/my_ansible/hosts
rm ~/virtualization/VMscripts/ID.txt
exit 0 
