#! /bin/bash
apt "update"
echo "Opennebula"
echo "deb https://downloads.opennebula.org/repo/5.4/Debian/8 stable opennebula" > /etc/apt/sources.list.d/opennebula.list
apt install opennebula
echo "ansible"
apt install ansible 
sh ~/virtualization/VMscripts/web
sh ~/virtualization/VMscripts/data
sh ~/virtualization/VMscripts/client
